name: YouTube Format List

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  list-formats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make yt-dlp executable
      run: chmod +x ./yt-dlp

    - name: List available formats with cookies
      run: |
        ./yt-dlp --cookies cookies.txt --no-playlist -F "${{ inputs.video_url }}" > formats.txt
    
    - name: Show format list
      run: cat formats.txt

