name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract 7-Zip (7z.tar.xz)
      run: |
        tar -xf 7z.tar.xz
        chmod +x ./7zz

    - name: Use 7zz to extract ffmpeg.7z and aria2
      run: |
        ./7zz x ffmpeg.7z -o./ffmpeg
        ./7zz x aria2.zip -o./ariac
        chmod +x ./ffmpeg/ffmpeg/ffmpeg
        chmod +x ./ffmpeg/ffmpeg/ffprobe
        chmod +x ./ariac/aria2/aria2c

    - name: Make yt-dlp executable
      run: chmod +x ./yt-dlp

    - name: Get video file size in bytes
      id: get_size
      run: |
        size=$("./yt-dlp" --cookies cookies.txt --no-playlist --print filesize "${{ inputs.video_url }}" || echo 0)
        echo "filesize=$size" >> $GITHUB_OUTPUT

    - name: Download video using yt-dlp with conditional downloader
      run: |
        if [ "${{ steps.get_size.outputs.filesize }}" -gt 300000000 ]; then
          echo "Big file detected (>300MB), using aria2c downloader"
          ./yt-dlp --downloader ./ariac/aria2/aria2c --downloader-args aria2c:"-x 16 -k 1M" --cookies cookies.txt --ffmpeg-location ./ffmpeg/ffmpeg --no-playlist -f "bv*+ba/b" --merge-output-format mp4 --output "download.%(ext)s" "${{ inputs.video_url }}"
        else
          echo "Small file detected (<=300MB), using default downloader"
          ./yt-dlp --cookies cookies.txt --ffmpeg-location ./ffmpeg/ffmpeg --no-playlist -f "bv*+ba/b" --merge-output-format mp4 --output "download.%(ext)s" "${{ inputs.video_url }}"
        fi

    - name: Upload downloaded video
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-video
        path: download.*
