name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  download-video:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run yt-dlp with cookies
      run: |
        echo "Downloading video: ${{ inputs.video_url }}"
        .\ytdlp.exe --cookies cookies.txt --no-playlist --output "%(title)s.%(ext)s" "${{ inputs.video_url }}"
