name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract 7-Zip (7z.tar.xz)
      run: |
        tar -xf 7z.tar.xz
        chmod +x ./7zz

    - name: Use 7zz to extract ffmpeg.7z
      run: |
        ./7zz x ffmpeg.7z -o./ffmpeg
        chmod +x ./ffmpeg/ffmpeg
        chmod +x ./ffmpeg/ffprobe
        ls -l ./ffmpeg
        echo "Searching for ffprobe:"
        find ./ffmpeg -iname "ffprobe*"

    - name: Make yt-dlp executable
      run: chmod +x ./yt-dlp

    - name: Download video using yt-dlp
      run: |
        echo "Downloading: ${{ inputs.video_url }}"
        ./yt-dlp --cookies cookies.txt --ffmpeg-location ./ffmpeg --no-playlist -f "bv*+ba/b" --merge-output-format mp4 --output "download.%(ext)s" "${{ inputs.video_url }}"

    - name: Upload downloaded video
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-video
        path: download.*
