name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        type: string

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Make yt-dlp executable
      run: chmod +x ./yt-dlp

    - name: Download video using yt-dlp
      run: |
        echo "Downloading video: ${{ inputs.video_url }}"
        ./yt-dlp --cookies cookies.txt --no-playlist -f "bestvideo+bestaudio" --merge-output-format mp4 --output "download.%(ext)s" "${{ inputs.video_url }}"

    - name: Upload video as artifact
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-video
        path: download.*
